#!/bin/bash

### BEGIN INIT INFO
# Provides:          cloud-set-guest-password
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Password Download Client
# Description:       Password Download Client
### END INIT INFO

#
# chkconfig: 2345 98 02
# description: Password Download Client
# processname: cloud-set-guest-password

#User whose password is changed. To change to 'administrator' under Ubuntu.
user=root

# Add your DHCP lease folders here
DHCP_FOLDERS="/var/lib/dhclient/* /var/lib/dhcp3/* /var/lib/dhcp/* /var/lib/NetworkManager/* /var/lib/dhcpcd/*"
password_received=0
file_count=0
error_count=0

if [ -r /etc/rc.d/init.d/functions ]; then
    . /etc/rc.d/init.d/functions
fi
if [ -r /lib/lsb/init-functions ]; then
    . /lib/lsb/init-functions
fi

echo "Starting Password Download Client"

case "$1" in
	start)
		for DHCP_FILE in $DHCP_FOLDERS ; do
			if [ -r $DHCP_FILE ] ; then
				logger -t "cloud" "DHCP_FILE : $DHCP_FILE"
				file_count=$((file_count+1))
				PASSWORD_SERVER_IP=`grep dhcp-server-identifier $DHCP_FILE | tail -n1 | awk '{print $NF}' | tr -d '\;'`
				logger -t "cloud" "PASSWORD_SERVER_IP : $PASSWORD_SERVER_IP"

				if [ -n "$PASSWORD_SERVER_IP" ] ; then
					sleep 3
					logger -t "cloud" "Found password server IP $PASSWORD_SERVER_IP in $DHCP_FILE"
					logger -t "cloud" "Sending request to password server at $PASSWORD_SERVER_IP"
					password=`wget -q -t 3 -T 20 -O - --header "DomU_Request: send_my_password" $PASSWORD_SERVER_IP:8080`
					password=`echo ${password} | tr -d '\r'`

					if [ $? -eq 0 ] ; then
						logger -t "cloud" "Got response from server at $PASSWORD_SERVER_IP"

						case $password in
						
							"")
								logger -t "cloud" "Password server at $PASSWORD_SERVER_IP did not have any password for the VM"
								continue
								;;
							"bad_request")
								logger -t "cloud" "VM sent an invalid request to password server at $PASSWORD_SERVER_IP"
								error_count=$((error_count+1))
								continue
								;;
							"saved_password")
								logger -t "cloud" "VM has already saved a password from the password server at $PASSWORD_SERVER_IP"
								continue
								;;
							*)
								logger -t "cloud" "VM got a valid password from server at $PASSWORD_SERVER_IP"
								password_received=1
								break
								;;			
						esac
					else
						logger -t "cloud" "Failed to send request to password server at $PASSWORD_SERVER_IP"
						error_count=$((error_count+1))
					fi
				else
					logger -t "cloud" "Could not find password server IP in $DHCP_FILE"
					error_count=$((error_count+1))
				fi
			fi
		done

		if [ $password_received -eq 0 ] ; then
			if [ $error_count -eq $file_count ] ; then
				logger -t "cloud" "Failed to get password from any server"
				exit 1
			else
				logger -t "cloud" "Did not need to change password."
				exit 0
			fi
		fi

		if [ $password_received -eq 1 ] ; then
			logger -t "cloud" "Changing password ..."
			echo ${user}:${password} | chpasswd
			# echo -e "${password}\n${password}" | (passwd ${user}) 2>&1 >> /dev/null
			if [ $? -eq 0 ] ; then
				logger -t "cloud" "Done changing password."
				logger -t "cloud" "Sending acknowledgment to password server at $PASSWORD_SERVER_IP"
				wget -q -t 3 -T 20 -O - --header "DomU_Request: saved_password" $PASSWORD_SERVER_IP:8080 2>&1 >> /dev/null
				logger -t "cloud" "Acknowledgment sent."
			else
				logger -t "cloud" "ERROR changing password."
				exit 1
			fi
		fi
		exit 0
        ;;
		
	restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;

	stop)
        # No-op
		exit 0
        ;;

	""|*)
        echo "Usage: /etc/init.d/cloud-set-guest-password {start|stop}" >&2
        exit 3
        ;;
esac
